
export interface OklchColor {
  l: number; // 0 to 1 (Lightness)
  c: number; // 0 to ~0.4 (Chroma)
  h: number; // 0 to 360 (Hue)
}

export interface HueDefinition {
  angle: number;
  id: string;
  nameEN: string;
  nameZH: string;
}

export interface ColorEntry {
  id: string;
  color: OklchColor;
  name: string; // The user input name (e.g., "寶寶藍")
  prefix?: string; // e.g., "淡"
  //baseName?: string; // e.g., "藍"
  votes: number;
  isSuspicious: boolean; // Flagged by AI
  suspiciousReason?: string;
  timestamp: number;
  isSeed?: boolean; // True if generated by the system, false if human input
}

export interface AggregatedCluster {
  name: string;
  centroid: { l: number; c: number };
  points: ColorEntry[];
  dominantPercentage: number; // e.g., 60%
  totalVotes: number;
}
